common:
  bigdata:
    hdfs:
      nameService: ns17
      nameNodes:
        nn1: 10.57.36.17:8020
        nn2: 10.57.36.18:8020
    hive:
      jdbcUrl: jdbc:hive2://10.57.36.18:10000
      username: hive
      password: hive
      pool:
        maxTotal: 20
        minIdle: 1
        maxIdle: 10
    hbase:
      hbaseHost: 10.57.36.17,10.57.36.18,10.57.36.19
      hbasePort: 2182
      hbaseZnode: /hbase
      kerberosEnable: false